version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: discord.js
    versions:
    - 12.5.1
    - 12.5.2
  - dependency-name: ytdl-core
    versions:
    - 4.4.5
  - dependency-name: enmap
    versions:
    - 5.8.4
  - dependency-name: cheerio
    versions:
    - 1.0.0-rc.5
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: canvas
    versions:
    - 2.6.1
